version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg13
    container_name: timescaledb
    environment:
      POSTGRES_DB: iot_data
      POSTGRES_USER: iot_data_user
      # Usa una contraseña dificil.
      POSTGRES_PASSWORD: P@ssw0rd_Gen3r@t3d$Hard
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always

volumes:
  timescaledb_data:
    driver: local
